### PR TITLE
adds recent articles

### PR DESCRIPTION
**Pull request by tr0njavolta**

### CODE REVIEW

**Comment by malisingh21** [comment]
Hey @tr0njavolta I checked again and this is the info we need to add to the header of the docs site:

"Here's the additional code you'll need to add to the codebase of your main website when embedding a stream for the tile styling to match the hub: [Codepen](https://codepen.io/mohitchoudhary1589/pen/vYbQQgy).  The code you see in the 'HTML window of this Codepen will change depending on the stream being embedded so you don't need to copy that portion over, only what's in the CSS window."

From there, we can add this code and it should give the latest 4 items (small version)
`

  <div id="UfEmbeddedHub1710886679404"></div>

  <script nonce="<?= $nonce ?>">
  window._ufHubConfig = window._ufHubConfig || [];
  window._ufHubConfig.push({
    'containers':{'app':'#UfEmbeddedHub1710886679404'},
    'collection': '11433137',
    'openLink':function(url){
      window.top.location.href=url;
    },
    'lazyloader':{
      'itemDisplayLimit':20,
      'maxTilesPerRow':4,
      'maxItemsTotal': 4
    },
    'tileSize': 'small',
    'enablePageTracking':false,
    'baseUrl': 'https://resources.upbound.io/',
    'filesUrl': 'https://resources.upbound.io/',
    'generatedAtUTC': '2024-03-19 22:17:49',
  });
  </script>

  <script nonce="<?= $nonce ?>">(function(d,t,u) {
    function load(){
      var s=d.createElement(t);s.src=u;d.body.appendChild(s);
    }
    if (window.addEventListener) {
      window.addEventListener('load',load,false);
    }
    else if (window.attachEvent) {
      window.attachEvent('onload',load);
    }
    else{
      window.onload=load;
    }
  }(document,'script','https://resources.upbound.io/hubsFront/embed_collection'));
  </script>
  `


LMK if that works – if not I'll get our CSM at Uberflip to help.

**Comment by tr0njavolta** [comment]
Should probably move this below the three row grid, before the "More" section or see if we can reduce the tiles vertically somehow.

**Comment by malisingh21** [comment]
@tr0njavolta I agree – Probably best to move it to the bottom. Unfortunately I can't change tile size within the platform – it only gives me a small, med, big option which I gave you the small. Maybe something we can change in the HTML? or even the CSS that we put on docs?

**Comment by tr0njavolta** [comment]
> @tr0njavolta I agree – Probably best to move it to the bottom. Unfortunately I can't change tile size within the platform – it only gives me a small, med, big option which I gave you the small. Maybe something we can change in the HTML? or even the CSS that we put on docs?

I think since this will likely change in the future, I want to keep this at the top and see if the placement produces an uptick in traffic.

**Pull request merged**
