### PR TITLE
Add ToC

### LINKED ISSUE #38: Add support for a page table of contents
[UP-92](https://upbound-unomena.atlassian.net/browse/UP-92)

Each page needs a right-hand table of contents similar to what is used in the [Hugo Book theme](https://hugo-book-demo.netlify.app/).

### PR DESCRIPTION
**Pull request by nicoleblom**
### Description of your changes
Added TableOfContents as side menu and added responsive styling

Fixes #38 
https://upbound-unomena.atlassian.net/browse/UP-92

### CODE REVIEW

**Comment by plumbis** [comment]
Thanks for this Nicole! It looks like a new grey box is being added above the central content. 
Screen Shot 2022-10-07 at 9 56 17 AM

Compare what's there today on the left with this PR on the right.

Can we get that fixed before merging?

**Comment by nicoleblom** [comment]
Fixed, thank you

**Comment by plumbis** [comment]
Found one more issue, not sure if it was there the first time, but it looks like all of the commands inside a code fence/box are being shifted down a line.

http://localhost:1313/quickstart/provider-aws/#bash-script

compared to:
https://docs.upbound.io/quickstart/provider-aws/#bash-script

**Comment by nicoleblom** [comment]
@plumbis  Thank you, reverted, and should reflect staging now, pushed to dev

**Comment by plumbis** [comment]
Looks good, merging to stage and will push this and the footer fix to main!

**Pull request merged**
