### PR TITLE
Move knowledge-base/migration doc to providers section

### PR DESCRIPTION
**Pull request by sergenyalcin**
This PR moves knowledge-base/migration doc to providers section.

### CODE REVIEW

**Comment by sergenyalcin** [comment]
We need to mention the new Just MR mode in the Automated Migration part. I plan to address this in a new PR. I think limiting the scope of this PR to consolidate only two documents will facilitate the review process.

**Review by jeanduplessis — COMMENTED** [review]
Could we please also delete the old knowledge base doc and add a redirect for the old page to the new place?

**Review by jeanduplessis — APPROVED** [review]

**Comment by plumbis** [comment]
This fails because of a `ref` link in `/content/providers/provider-familiies.md`

Change this line
https://github.com/sergenyalcin/docs/blob/mono-to-family-2/content/providers/provider-families.md?plain=1#L26

to 
`[family providers migration guide]({{<ref “/providers/migration”>}})`

**Comment by sergenyalcin** [comment]
I validated the "knowledge-base/migrate-to-provider-families" link is redirected to the new path.

**Pull request merged**
